### ISSUE TITLE
[bug report] an error is reported when downloading the topic function in the online topic generation tool

### ISSUE THREAD

**Issue by yiduoduopijing** [element-plus/theme-chalk-preview#10]
### Element Plus version
1.1.0-beta.8

### OS/Browsers version
Chrome 92

### Vue version
3.2.8

### Reproduction Link
https://element-plus.github.io/theme-chalk-preview/#/zh-CN

### Steps to reproduce
TypeError: Cannot read property 'forEach' of null

### What is Expected?
可以恢复在线主题下载功能

### What is actually happening?
TypeError: Cannot read property 'forEach' of null

**Comment by sxzz** [comment]
This problem seems to have been fixed, please try.
