### ISSUE TITLE
Failed to download theme pack from the preview site

### ISSUE THREAD

**Issue by ShookLyngs** [element-plus/theme-chalk-preview#14]
URL: 
https://element-plus.github.io/theme-chalk-preview/#/zh-CN

Description:
I tried to generate a theme pack for my new project, but when I clicked the 'Download Theme' button after setting the theme color, nothing happened.
Then I found some error was printed in the console.

Console logs:
```
unpkg.com/element-plus@1.1.0-beta.21/dist/fonts/element-icons.woff:1 Failed to load resource: the server responded with a status of 404 ()
unpkg.com/element-plus@1.1.0-beta.21/dist/fonts/element-icons.ttf:1 Failed to load resource: the server responded with a status of 404 ()
index.e7969d6e.js:15 Uncaught (in promise) Error
    at XMLHttpRequest.r.onreadystatechange (index.e7969d6e.js:15)
element-plus.github.io/:1 GET https://element-plus.github.io/theme-chalk-preview/fonts/element-icons.woff net::ERR_ABORTED 404
element-plus.github.io/:1 GET https://element-plus.github.io/theme-chalk-preview/fonts/element-icons.ttf net::ERR_ABORTED 404
vendor.182576ce.js:1 TypeError: Cannot read property 'forEach' of null
    at K (index.e7969d6e.js:15)
    at yn (vendor.182576ce.js:1)
    at xt (vendor.182576ce.js:1)
    at HTMLLIElement.n (vendor.182576ce.js:1)
```

**Comment by YunYouJun** [comment]
🤔 hmm, this project was migrated following element-ui. As element-plus continues to update, I feel like it's almost dead, and we should refactor it when we're done with the full version of element-plus.

**Comment by sxzz** [comment]
I upgraded it the few days ago. This problem should caused by `element-plus@21`, you should upgrade to the latest version.
