### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by iamkun** [element-plus/theme-chalk-preview#3]
Hi @WsmDyj

I've merged your PR and it looks good in my local environment.

However, there is a build error in the Github Action while running `npm run build` https://github.com/element-plus/theme-chalk-preview/runs/2379732903?check_suite_focus=true

![image](https://user-images.githubusercontent.com/17680888/115220480-2a509a80-a13b-11eb-830e-7983c991b7d2.png)

Can you please take a look?

**Comment by WsmDyj** [comment]
你在本地执行`npm run build`有错误吗

**Comment by WsmDyj** [comment]
这看起来是element-plus 语言包导致的，我将如何复现您的问题，或者您本地直接执行`npm run deploy`不走gh-page.yml配置会有问题吗

**Comment by WsmDyj** [comment]
@iamkun 
我解决了这个bug并且test后重新提了pr，你可以合一下，应该没问题，主要问题是lang包地址不对，导致打包找不到

![success](https://img10.360buyimg.com/imagetools/jfs/t1/176121/34/5354/272337/607d73dcEa0a52831/fa2edcd3e5996b54.png)

**Comment by iamkun** [comment]
cool, the site is available at https://element-plus.github.io/theme-chalk-preview

You may update the PR https://github.com/element-plus/element-plus/pull/1861 using this URL.
